version: "3"

services:
  server:
    image: wuzhenhua/ambari-server
    container_name: ambari-server.wuzhenhua.cn
    networks:
      - ambari-tier
    ports:
      - 8080:8080
      - 3000:3000
    domainname: wuzhenhua.cn
    hostname: ambari-server
    privileged: true
  agent1:
    image: wuzhenhua/ambari-base
    container_name: agent1.wuzhenhua.cn
    networks:
      - ambari-tier
    domainname: wuzhenhua.cn
    hostname: agent1
    privileged: true
  agent2:
    image: wuzhenhua/ambari-base
    container_name: agent2.wuzhenhua.cn
    networks:
      - ambari-tier
    domainname: wuzhenhua.cn
    hostname: agent2
    privileged: true
networks:
  ambari-tier:
